---
- name: "My third play"
  hosts: logicservers
  serial: 1

  tasks:

  - name: "Shutdown server "
    debug: 
      msg: "Shutdown {{ inventory_hostname }}"

  - name: "Upgrade firmware "
    debug: 
      msg: "Upgrade {{ inventory_hostname }}"

  - name: "Start server "
    debug: 
      msg: "Start {{ inventory_hostname }}"  